### PR TITLE
Update for coding standards as I review the codebase.

### PR DESCRIPTION
**Pull request by m4olivei**
As I review and evaluate the codebase for our use, I've been cleaning up some codings standards and fleshing out documentation.

### CODE REVIEW

**Comment by m4olivei** [comment]
cc @nignatov 

Is this valuable to you? Should I create an issue on d.o for it?

**Comment by nignatov** [comment]
@m4olivei for me it doesn't matter and I think it is not necessary.

**Comment by m4olivei** [comment]
But it's so much easier to read through, and with better PHPStorm support for auto-completion.

Pleeeeeeassse consider it? :)

**Comment by nignatov** [comment]
Yes, sure and I love the standards. I will take a look later today and merge it if everything OK :)

**Comment by m4olivei** [comment]
w00t!

**Comment by m4olivei** [comment]
Thanks @nignatov! I'd love your thoughts on this issue: https://www.drupal.org/node/2910630

Also, a couple of us Lullabots are working on the elasticsearch_connector module for a client and have time to put some work into it. Do you happen to hang out in IRC/Slack or some place where we can hit you up with questions? If not that's cool, we can just continue using the issue queue and Github to communicate over specific issues.

**Comment by nignatov** [comment]
@m4olivei, yes I'm using Slack and I'm in the Drupal channel so you can point your questions there. I would love to answer them when have time and happy that you are working on the module.

**Pull request merged**
